// Exact job-label mappings generated by STMO query 127887.
'use strict';

function indexPerformanceAlerts(rows) {
    if (!Array.isArray(rows) || !rows.length) throw new Error('Alert results are empty');
    const index = new Map();
    for (const row of rows) {
        if (row.schema_version !== 3 || typeof row.sheriffing_enabled !== 'boolean' || typeof row.job_label !== 'string' ||
            typeof row.repository !== 'string' || !Array.isArray(row.bug_ids) ||
            !Array.isArray(row.regression_bug_ids) || row.regression_bug_ids.some(id => !row.bug_ids.includes(id)) ||
            !Array.isArray(row.fixed_bug_ids) || !row.window_start || !row.generated_at ||
            row.bug_count !== new Set(row.bug_ids).size ||
            row.fixed_bug_count !== new Set(row.fixed_bug_ids).size ||
            row.fixed_bug_ids.some(id => !row.bug_ids.includes(id))) {
            throw new Error('Alert results have an unsupported or inconsistent format');
        }
        const key = JSON.stringify([row.repository, row.job_label]);
        if (index.has(key)) throw new Error('Duplicate job mapping in alert results');
        index.set(key, row);
    }
    return index;
}

function countPerformanceAlerts(runs, index) {
    const configurations = new Map();
    for (const run of runs) configurations.set(JSON.stringify([run.project, run.label]), run);
    const alerts = new Set();
    const fixed = new Set();
    let mapped = 0;
    let sheriffingEnabled = false;
    for (const key of configurations.keys()) {
        const match = index.get(key);
        if (!match) continue;
        mapped++;
        sheriffingEnabled ||= match.sheriffing_enabled;
        match.regression_bug_ids.forEach(id => alerts.add(id));
        match.fixed_bug_ids.filter(id => match.regression_bug_ids.includes(id)).forEach(id => fixed.add(id));
    }
    return { bugIds: [...alerts].sort((a, b) => a - b), fixedBugIds: [...fixed].sort((a, b) => a - b), sheriffingEnabled, total: alerts.size, fixed: fixed.size, mapped, configurations: configurations.size };
}

const performanceAlertsState = { status: 'loading', index: null, error: '', windowStart: '', generatedAt: '' };
let performanceAlertCells = [];

const BUG_RESOLUTIONS = [
    ['Fixed', '#2a78d6'], ["Won’t fix", '#eb6834'], ['Invalid', '#1baf7a'],
    ['Duplicate', '#eda100'], ['Works for me', '#4a3aa7'], ['Other', '#e87ba4'],
    ['Open', '#008300'], ['Unknown', '#c5c5c5'],
];
const bugResolutions = new Map();
let bugResolutionsLoading = false;

function bugResolution(bug) {
    if (!bug || typeof bug.resolution !== 'string') return 'Unknown';
    return ({ FIXED: 'Fixed', WONTFIX: 'Won’t fix', INVALID: 'Invalid', DUPLICATE: 'Duplicate',
        WORKSFORME: 'Works for me', '': 'Open' })[bug.resolution] || 'Other';
}

async function loadBugResolutions(url) {
    bugResolutionsLoading = true;
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 30000);
    try {
        const response = await fetch(url, { signal: controller.signal });
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const data = await response.json();
        const rows = data.query_result?.data?.rows;
        if (!Array.isArray(rows)) throw new Error('Unsupported resolution results');
        for (const bug of rows) {
            if (Number.isInteger(bug.id)) bugResolutions.set(bug.id, bugResolution(bug));
        }
    } catch { /* Missing or inaccessible bugs remain explicitly unknown. */ }
    finally {
        clearTimeout(timeout);
        bugResolutionsLoading = false;
        updatePerformanceAlertCells();
    }
}

function updatePerformanceAlertCells() {
    for (const { runs, totalCell } of performanceAlertCells) {
        if (performanceAlertsState.status !== 'ready') {
            totalCell.textContent = performanceAlertsState.status === 'loading' ? '…' : '—';
            totalCell.title = performanceAlertsState.status === 'loading' ? 'Loading bugs' : performanceAlertsState.error;
            continue;
        }
        const counts = countPerformanceAlerts(runs, performanceAlertsState.index);
        const breakdown = new Map(BUG_RESOLUTIONS.map(([name]) => [name, 0]));
        for (const id of counts.bugIds) {
            const name = bugResolutions.get(id) || 'Unknown';
            breakdown.set(name, breakdown.get(name) + 1);
        }
        totalCell.removeAttribute('title');
        totalCell.textContent = counts.mapped ? '0' : '—';
        if (!counts.total) continue;
        const container = document.createElement('div');
        container.className = 'resolution-widget';
        const trigger = document.createElement('button');
        trigger.type = 'button';
        trigger.className = 'resolution-trigger';
        trigger.setAttribute('aria-label', 'Show bug resolution breakdown');
        trigger.setAttribute('aria-expanded', 'false');
        const popup = document.createElement('div');
        popup.className = 'resolution-tooltip';
        popup.hidden = true;
        for (const [name, color] of BUG_RESOLUTIONS) {
            const ids = counts.bugIds.filter(id => (bugResolutions.get(id) || 'Unknown') === name);
            const line = document.createElement('div');
            const swatch = document.createElement('span');
            swatch.className = 'resolution-swatch';
            swatch.style.backgroundColor = color;
            const text = document.createElement('span');
            text.textContent = `${name}: `;
            const number = document.createElement(ids.length ? 'a' : 'span');
            number.textContent = String(ids.length);
            if (ids.length) {
                const url = new URL('https://bugzilla.mozilla.org/buglist.cgi');
                url.searchParams.set('bug_id', ids.join(','));
                number.href = url.href;
                number.target = '_blank';
                number.rel = 'noopener noreferrer';
                number.setAttribute('aria-label', `${name}: ${ids.length} bugs`);
            }
            line.append(swatch, text, number);
            popup.appendChild(line);
        }
        const show = () => {
            popup.hidden = false;
            const rect = trigger.getBoundingClientRect();
            popup.style.left = `${Math.max(8, Math.min(rect.left, window.innerWidth - popup.offsetWidth - 8))}px`;
            popup.style.top = `${rect.bottom + popup.offsetHeight < window.innerHeight ? rect.bottom : Math.max(8, rect.top - popup.offsetHeight)}px`;
            trigger.setAttribute('aria-expanded', 'true');
        };
        const hide = () => { popup.hidden = true; trigger.setAttribute('aria-expanded', 'false'); };
        container.addEventListener('mouseenter', show);
        container.addEventListener('mouseleave', hide);
        container.addEventListener('focusin', show);
        container.addEventListener('focusout', event => { if (!container.contains(event.relatedTarget)) hide(); });
        container.addEventListener('keydown', event => { if (event.key === 'Escape') { hide(); event.stopPropagation(); } });
        container.addEventListener('click', event => event.stopPropagation());
        trigger.addEventListener('click', show);
        const bar = document.createElement('span');
        bar.className = 'resolution-bar';
        bar.setAttribute('aria-hidden', 'true');
        for (const [name, color] of BUG_RESOLUTIONS) {
            const count = breakdown.get(name);
            if (!count) continue;
            const segment = document.createElement('span');
            segment.style.flexGrow = String(count);
            segment.style.backgroundColor = color;
            bar.appendChild(segment);
        }
        const label = document.createElement('span');
        label.className = 'resolution-total';
        label.textContent = counts.total.toLocaleString();
        trigger.append(bar, label);
        container.append(trigger, popup);
        totalCell.replaceChildren(container);
    }
}

async function loadPerformanceAlerts() {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 60000);
    try {
        const configResponse = await fetch('./performance-alerts-source.json', { signal: controller.signal });
        if (!configResponse.ok) throw new Error(`Alert configuration: HTTP ${configResponse.status}`);
        const config = await configResponse.json();
        const response = await fetch(config.results_url, { signal: controller.signal });
        if (!response.ok) throw new Error(`Alert results: HTTP ${response.status}`);
        const result = await response.json();
        const rows = result.query_result?.data?.rows;
        performanceAlertsState.index = indexPerformanceAlerts(rows);
        performanceAlertsState.status = 'ready';
        performanceAlertsState.windowStart = rows[0].window_start;
        performanceAlertsState.generatedAt = rows[0].generated_at;
        loadBugResolutions(config.resolutions_results_url);
    } catch (error) {
        performanceAlertsState.status = 'error';
        performanceAlertsState.error = `Bug counts unavailable: ${error.message}`;
    } finally {
        clearTimeout(timeout);
        updatePerformanceAlertCells();
        if (typeof performanceSort !== 'undefined' && ['alerts', 'fixed'].includes(performanceSort.key)
            && !document.getElementById('test-search').disabled) renderPerformance();
    }
}
