// Exact job-label mappings generated by STMO query 127887.
'use strict';

function indexPerformanceAlerts(rows) {
    if (!Array.isArray(rows) || !rows.length) throw new Error('Alert results are empty');
    const index = new Map();
    for (const row of rows) {
        if (row.schema_version !== 3 || typeof row.sheriffing_enabled !== 'boolean' || typeof row.job_label !== 'string' ||
            typeof row.repository !== 'string' || !Array.isArray(row.bug_ids) ||
            !Array.isArray(row.fixed_bug_ids) || !row.window_start || !row.generated_at ||
            row.bug_count !== new Set(row.bug_ids).size ||
            row.fixed_bug_count !== new Set(row.fixed_bug_ids).size ||
            row.fixed_bug_ids.some(id => !row.bug_ids.includes(id))) {
            throw new Error('Alert results have an unsupported or inconsistent format');
        }
        const key = JSON.stringify([row.repository, row.job_label]);
        if (index.has(key)) throw new Error('Duplicate job mapping in alert results');
        index.set(key, row);
    }
    return index;
}

function countPerformanceAlerts(runs, index) {
    const configurations = new Map();
    for (const run of runs) configurations.set(JSON.stringify([run.project, run.label]), run);
    const alerts = new Set();
    const fixed = new Set();
    let mapped = 0;
    let sheriffingEnabled = false;
    for (const key of configurations.keys()) {
        const match = index.get(key);
        if (!match) continue;
        mapped++;
        sheriffingEnabled ||= match.sheriffing_enabled;
        match.bug_ids.forEach(id => alerts.add(id));
        match.fixed_bug_ids.forEach(id => fixed.add(id));
    }
    return { bugIds: [...alerts].sort((a, b) => a - b), fixedBugIds: [...fixed].sort((a, b) => a - b), sheriffingEnabled, total: alerts.size, fixed: fixed.size, mapped, configurations: configurations.size };
}

const performanceAlertsState = { status: 'loading', index: null, error: '', windowStart: '', generatedAt: '' };
let performanceAlertCells = [];

function updatePerformanceAlertCells() {
    for (const { runs, totalCell, fixedCell } of performanceAlertCells) {
        if (performanceAlertsState.status !== 'ready') {
            for (const cell of [totalCell, fixedCell]) {
                cell.textContent = performanceAlertsState.status === 'loading' ? '…' : '—';
                cell.title = performanceAlertsState.status === 'loading' ? 'Loading yearly bug counts' : performanceAlertsState.error;
            }
            continue;
        }
        const counts = countPerformanceAlerts(runs, performanceAlertsState.index);
        const partial = counts.mapped < counts.configurations;
        for (const [cell, value] of [[totalCell, counts.total], [fixedCell, counts.fixed]]) {
            cell.textContent = !counts.mapped ? '—' : value.toLocaleString();
            if (counts.mapped && value > 0) {
                const link = document.createElement('a');
                link.className = 'bug-count';
                link.textContent = value.toLocaleString();
                const name = cell.parentElement.cells[0].title;
                link.setAttribute('aria-label', `Open ${cell === fixedCell ? 'fixed bugs' : 'bugs'} for ${name} in Bugzilla`);
                const url = new URL('https://bugzilla.mozilla.org/buglist.cgi');
                url.searchParams.set('bug_id', (cell === fixedCell ? counts.fixedBugIds : counts.bugIds).join(','));
                link.href = url.href;
                link.target = '_blank';
                link.rel = 'noopener noreferrer';
                cell.replaceChildren(link);
            }
            cell.title = `${counts.mapped} of ${counts.configurations} job/repository configurations mapped. ` +
                (partial ? 'Unmapped jobs are unknown, not zero. Counts are a lower bound. ' : '') +
                'Distinct bugs linked to alerts created in the cached 365-day window for signatures from up to three recent successful runs. Bug creation dates are not used. Retired or unsampled signatures may be absent. ' +
                (cell === fixedCell ? 'Fixed counts linked bugs with at least one non-invalid alert whose effective summary is Fixed or whose cached bug resolution is FIXED or DUPLICATE. This is not a complete check of current Bugzilla status.' : 'Deduplicates bug IDs across all included alerts, including improvements and all triage statuses.');
        }
    }
}

async function loadPerformanceAlerts() {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 60000);
    try {
        const configResponse = await fetch('./performance-alerts-source.json', { signal: controller.signal });
        if (!configResponse.ok) throw new Error(`Alert configuration: HTTP ${configResponse.status}`);
        const config = await configResponse.json();
        const response = await fetch(config.results_url, { signal: controller.signal });
        if (!response.ok) throw new Error(`Alert results: HTTP ${response.status}`);
        const result = await response.json();
        const rows = result.query_result?.data?.rows;
        performanceAlertsState.index = indexPerformanceAlerts(rows);
        performanceAlertsState.status = 'ready';
        performanceAlertsState.windowStart = rows[0].window_start;
        performanceAlertsState.generatedAt = rows[0].generated_at;
    } catch (error) {
        performanceAlertsState.status = 'error';
        performanceAlertsState.error = `Bug counts unavailable: ${error.message}`;
    } finally {
        clearTimeout(timeout);
        updatePerformanceAlertCells();
        if (typeof performanceSort !== 'undefined' && ['alerts', 'fixed'].includes(performanceSort.key)
            && !document.getElementById('test-search').disabled) renderPerformance();
    }
}
